// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {proxy} from '../models';

export function ClearCapturedRequests():Promise<void>;

export function ForceRestartChrome():Promise<void>;

export function GetCapturedRequests():Promise<Array<proxy.CapturedRequest>>;

export function GetStatus():Promise<Record<string, any>>;

export function InstallCA():Promise<void>;

export function IsCATrusted():Promise<boolean>;

export function LaunchChrome():Promise<void>;

export function StartCapture():Promise<void>;

export function StopCapture():Promise<void>;
