// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCapturedRequests() {
  return window['go']['main']['App']['ClearCapturedRequests']();
}

export function ForceRestartChrome() {
  return window['go']['main']['App']['ForceRestartChrome']();
}

export function GetCapturedRequests() {
  return window['go']['main']['App']['GetCapturedRequests']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function InstallCA() {
  return window['go']['main']['App']['InstallCA']();
}

export function IsCATrusted() {
  return window['go']['main']['App']['IsCATrusted']();
}

export function LaunchChrome() {
  return window['go']['main']['App']['LaunchChrome']();
}

export function StartCapture() {
  return window['go']['main']['App']['StartCapture']();
}

export function StopCapture() {
  return window['go']['main']['App']['StopCapture']();
}
